### ISSUE TITLE
Consider adding `logical_xor` to mathematical functions

### ISSUE THREAD

**Issue by jlalbers** [dwavesystems/dwave-optimization#125]
Currently, an XOR symbol can be created by composing different logical function symbols, i.e.:
```python
sym_1 = model.binary(...)
sym_2 = model.binary(...)
xor = logical_and(
    logical_not(logical_and(sym_1, sym_2)),
    logical_or(sym_1, sym_2)
)
...
```
However, I imagine it would be more efficient and expressive to have a separate XOR symbol.

**Comment by arcondello** [comment]
Do you have a specific use case in mind? I agree it could be there for symmetry, but I'd like to add new nodes lazily rather than eagerly.
