### ISSUE TITLE
Model.to_networkx() example uses local path to figure

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dwave-optimization#64]
The [/_images/to_networkx_example.svg path here](https://github.com/dwavesystems/dwave-optimization/blob/125a1ffab2aefb45e6d7f62d0769f78f5437a16c/dwave/optimization/model.pyx#L878) works for local builds but not for the SDK build, where it is translated to `dwave-ocean-sdk/docs/_build/html/docs_optimization/reference/generated/_images/to_networkx_example.svg` and not found.

I've tried a few alternatives but so far haven't a good solution. Depending on when there's a new SDK release we might need to remove this or move it to the intro.

**Comment by arcondello** [comment]
symbolic link to the image in the SDK's `_images/` maybe? Another option would be "hosting" the image somewhere (even just in this issue) and linking it from the docs. Both ugly for sure.

**Comment by JoelPasvolsky** [comment]
Yes, I was looking at symbolic links and considering putting the image in the SDK with the normal path so it would only build there (and give an error for local builds)

**Comment by arcondello** [comment]
Ah, we can also reference it with a URL like https://github.com/dwavesystems/dwave-optimization/blob/main/docs/_images/to_networkx_example.svg. Obviously makes updating a pain but :shrug:

**Comment by randomir** [comment]
I would avoid "hotlinking" to github. Symlink seems the way to go.

**Comment by JoelPasvolsky** [comment]
Perhaps there's a different syntax but directly using the URL creates a link that you have to open to see the image
![image](https://github.com/user-attachments/assets/d14f204a-5b05-4975-80ce-14555873e3aa)

**Comment by randomir** [comment]
You'd need to link to the raw image: https://raw.githubusercontent.com/dwavesystems/dwave-optimization/main/docs/_images/to_networkx_example.svg, but that's frowned upon.

**Comment by JoelPasvolsky** [comment]
Looks like it's actually enough to have the image itself under [sdk _images](https://github.com/dwavesystems/dwave-ocean-sdk/tree/master/docs/_images) for the absolute path (which is currently used in dwave-optimization) to work. I should have tried that first. 

I suggest adding that image as part of [this PR](https://github.com/dwavesystems/dwave-ocean-sdk/pull/300) and making a PR in dwave-optimization to replace the [current image](https://github.com/dwavesystems/dwave-optimization/blob/main/docs/_images/to_networkx_example.svg) with an image that gives the new location so in the future the right one is updated

**Comment by arcondello** [comment]
> replace the [current image](https://github.com/dwavesystems/dwave-optimization/blob/main/docs/_images/to_networkx_example.svg) with an image that gives the new location so in the future the right one is updated

I don't understand what you mean by this

**Comment by JoelPasvolsky** [comment]
Local build of dwave-optimization:
![image](https://github.com/user-attachments/assets/b96fd207-f7c7-43f4-888e-87c7f70a91b1)

SDK build:
![image](https://github.com/user-attachments/assets/34fcd7eb-35d2-49f6-b3ea-e463bb6be154)

**Comment by arcondello** [comment]
I would prefer to keep the image locally and use a symbolic link in the SDK rather than have the local doc builds not work. I also don't love absolute paths for the image.

**Comment by JoelPasvolsky** [comment]
Okay, for some reason the first time I built that it failed with an error `WARNING: cannot copy static file FileExistsError(17, 'File exists')` but after cleaning old generated files a second build works nicely. 

[This commit](https://github.com/JoelPasvolsky/dwave-ocean-sdk/commit/a39bf3202f9bb6d85c642a6d854201e86fcf0495) closes this issue.
